const COLOR_AZUL_CLARO = '#0096ff';
const COLOR_GRIS = '#B1B1B1';
const COLOR_PURPURA = '#5916bc';
const COLOR_VERDE = '#00D28A';
const COLOR_NEGRO = '#434349';
const LIGHT_GRAY = '#959CB6';
const COLOR_AZUL_OSCURO = '#032f61';
const DARK_GREEN = '#0D9910';
const COLOR_ROJO = '#dd1144';
const COLOR_AMARILLO = '#ffc200';

export {
  COLOR_AZUL_CLARO,
  COLOR_PURPURA,
  COLOR_VERDE,
  COLOR_NEGRO, 
  LIGHT_GRAY,
  COLOR_GRIS, 
  COLOR_AZUL_OSCURO,
  DARK_GREEN,
  COLOR_ROJO,
  COLOR_AMARILLO
};